server:
  port: 8070

spring:
  application:
    name: melody-config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/melody2017/melody-config.git
          username: melody2017
          password: ismp.1314